/**
 * Modulverzeichnis.
 *
 * Eine einzige Liste bestimmt Navigation, Adressen, Symbole und Gruppierung.
 * Ein neues Modul wird hier eingetragen und erscheint ueberall - in der
 * Seitenleiste, in der Telefonnavigation und in der globalen Suche.
 */
import {
  Boxes,
  Brush,
  Building2,
  CalendarClock,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  DoorClosed,
  Droplets,
  FileSignature,
  FileSpreadsheet,
  FileText,
  Files,
  Gauge,
  Home,
  KeyRound,
  LayoutDashboard,
  ListChecks,
  MapPin,
  MessageSquareWarning,
  Network,
  PackageSearch,
  type LucideIcon,
  Receipt,
  Settings,
  Sun,
  ShieldAlert,
  ShieldCheck,
  SprayCan,
  Truck,
  UserCog,
  Users,
  Wrench,
  Zap,
} from 'lucide-react';

import { TranslationKey } from '@/lib/i18n/dictionary';
import { CollectionKey, ModuleKey } from '@/lib/types';

export type NavGroup = 'overview' | 'objects' | 'work' | 'cleaning' | 'business' | 'system';

export interface ModuleDefinition {
  key: ModuleKey;
  /** Sammlung in der Datenschicht; fehlt bei Dashboard, Berichte und Einstellungen. */
  collection?: CollectionKey;
  path: string;
  icon: LucideIcon;
  group: NavGroup;
  labelKey: TranslationKey;
  singularKey: TranslationKey;
}

export const MODULES: ModuleDefinition[] = [
  {
    key: 'dashboard',
    path: '/dashboard',
    icon: LayoutDashboard,
    group: 'overview',
    labelKey: 'module.dashboard',
    singularKey: 'module.dashboard',
  },
  {
    key: 'calendar',
    path: '/calendar',
    icon: CalendarDays,
    group: 'overview',
    labelKey: 'module.calendar',
    singularKey: 'module.calendar',
  },
  {
    key: 'today',
    path: '/today',
    icon: Sun,
    group: 'overview',
    labelKey: 'module.today',
    singularKey: 'module.today',
  },
  {
    key: 'customers',
    collection: 'customers',
    path: '/customers',
    icon: Users,
    group: 'objects',
    labelKey: 'module.customers',
    singularKey: 'module.customers.singular',
  },
  {
    key: 'suppliers',
    collection: 'suppliers',
    path: '/suppliers',
    icon: Truck,
    group: 'objects',
    labelKey: 'module.suppliers',
    singularKey: 'module.suppliers.singular',
  },
  {
    key: 'organizations',
    collection: 'organizations',
    path: '/organizations',
    icon: Network,
    group: 'objects',
    labelKey: 'module.organizations',
    singularKey: 'module.organizations.singular',
  },
  {
    key: 'sites',
    collection: 'sites',
    path: '/sites',
    icon: MapPin,
    group: 'objects',
    labelKey: 'module.sites',
    singularKey: 'module.sites.singular',
  },
  {
    key: 'properties',
    collection: 'properties',
    path: '/properties',
    icon: Home,
    group: 'objects',
    labelKey: 'module.properties',
    singularKey: 'module.properties.singular',
  },
  {
    key: 'buildings',
    collection: 'buildings',
    path: '/buildings',
    icon: Building2,
    group: 'objects',
    labelKey: 'module.buildings',
    singularKey: 'module.buildings.singular',
  },
  {
    key: 'rooms',
    collection: 'rooms',
    path: '/rooms',
    icon: DoorClosed,
    group: 'objects',
    labelKey: 'module.rooms',
    singularKey: 'module.rooms.singular',
  },
  {
    key: 'assets',
    collection: 'assets',
    path: '/assets',
    icon: Boxes,
    group: 'objects',
    labelKey: 'module.assets',
    singularKey: 'module.assets.singular',
  },
  {
    key: 'documents',
    collection: 'documents',
    path: '/documents',
    icon: Files,
    group: 'objects',
    labelKey: 'module.documents',
    singularKey: 'module.documents.singular',
  },
  {
    key: 'energy',
    collection: 'energy',
    path: '/energy',
    icon: Gauge,
    group: 'objects',
    labelKey: 'module.energy',
    singularKey: 'module.energy.singular',
  },
  {
    key: 'keys',
    collection: 'keys',
    path: '/keys',
    icon: KeyRound,
    group: 'objects',
    labelKey: 'module.keys',
    singularKey: 'module.keys.singular',
  },
  {
    key: 'stock',
    collection: 'stock',
    path: '/stock',
    icon: PackageSearch,
    group: 'objects',
    labelKey: 'module.stock',
    singularKey: 'module.stock.singular',
  },
  {
    key: 'contracts',
    collection: 'contracts',
    path: '/contracts',
    icon: FileSignature,
    group: 'business',
    labelKey: 'module.contracts',
    singularKey: 'module.contracts.singular',
  },
  {
    key: 'orders',
    collection: 'orders',
    path: '/orders',
    icon: ClipboardList,
    group: 'work',
    labelKey: 'module.orders',
    singularKey: 'module.orders.singular',
  },
  {
    key: 'maintenances',
    collection: 'maintenances',
    path: '/maintenances',
    icon: Wrench,
    group: 'work',
    labelKey: 'module.maintenances',
    singularKey: 'module.maintenances.singular',
  },
  {
    key: 'legionella',
    collection: 'legionella',
    path: '/legionella',
    icon: Droplets,
    group: 'work',
    labelKey: 'module.legionella',
    singularKey: 'module.legionella.singular',
  },
  {
    key: 'rcd',
    collection: 'rcd',
    path: '/rcd',
    icon: Zap,
    group: 'work',
    labelKey: 'module.rcd',
    singularKey: 'module.rcd.singular',
  },
  {
    key: 'damages',
    collection: 'damages',
    path: '/damages',
    icon: ShieldAlert,
    group: 'work',
    labelKey: 'module.damages',
    singularKey: 'module.damages.singular',
  },
  {
    key: 'reports',
    collection: 'reports',
    path: '/reports',
    icon: FileText,
    group: 'work',
    labelKey: 'module.reports',
    singularKey: 'module.reports.singular',
  },
  {
    key: 'quotes',
    collection: 'quotes',
    path: '/quotes',
    icon: FileSpreadsheet,
    group: 'business',
    labelKey: 'module.quotes',
    singularKey: 'module.quotes.singular',
  },
  {
    key: 'invoices',
    collection: 'invoices',
    path: '/invoices',
    icon: Receipt,
    group: 'business',
    labelKey: 'module.invoices',
    singularKey: 'module.invoices.singular',
  },
  {
    key: 'cleaning',
    path: '/cleaning',
    icon: SprayCan,
    group: 'cleaning',
    labelKey: 'module.cleaning',
    singularKey: 'module.cleaning',
  },
  {
    key: 'cleaningtasks',
    collection: 'cleaningtasks',
    path: '/cleaning/tasks',
    icon: ListChecks,
    group: 'cleaning',
    labelKey: 'module.cleaningtasks',
    singularKey: 'module.cleaningtasks.singular',
  },
  {
    key: 'cleaningplans',
    collection: 'cleaningplans',
    path: '/cleaning/plans',
    icon: CalendarClock,
    group: 'cleaning',
    labelKey: 'module.cleaningplans',
    singularKey: 'module.cleaningplans.singular',
  },
  {
    key: 'cleaningareas',
    collection: 'cleaningareas',
    path: '/cleaning/areas',
    icon: Brush,
    group: 'cleaning',
    labelKey: 'module.cleaningareas',
    singularKey: 'module.cleaningareas.singular',
  },
  {
    key: 'cleaners',
    collection: 'cleaners',
    path: '/cleaning/staff',
    icon: Users,
    group: 'cleaning',
    labelKey: 'module.cleaners',
    singularKey: 'module.cleaners.singular',
  },
  {
    key: 'cleaningchecks',
    collection: 'cleaningchecks',
    path: '/cleaning/checks',
    icon: ClipboardCheck,
    group: 'cleaning',
    labelKey: 'module.cleaningchecks',
    singularKey: 'module.cleaningchecks.singular',
  },
  {
    key: 'cleaningcomplaints',
    collection: 'cleaningcomplaints',
    path: '/cleaning/complaints',
    icon: MessageSquareWarning,
    group: 'cleaning',
    labelKey: 'module.cleaningcomplaints',
    singularKey: 'module.cleaningcomplaints.singular',
  },
  {
    key: 'analytics',
    path: '/analytics',
    icon: FileSpreadsheet,
    group: 'business',
    labelKey: 'module.analytics',
    singularKey: 'module.analytics',
  },
  {
    key: 'audit',
    path: '/audit',
    icon: ClipboardCheck,
    group: 'work',
    labelKey: 'module.audit',
    singularKey: 'module.audit',
  },
  {
    key: 'users',
    collection: 'users',
    path: '/users',
    icon: UserCog,
    group: 'system',
    labelKey: 'module.users',
    singularKey: 'module.users.singular',
  },
  {
    key: 'activities',
    collection: 'activities',
    path: '/activities',
    icon: ShieldCheck,
    group: 'system',
    labelKey: 'module.activities',
    singularKey: 'module.activities.singular',
  },
  {
    key: 'settings',
    path: '/settings',
    icon: Settings,
    group: 'system',
    labelKey: 'module.settings',
    singularKey: 'module.settings',
  },
];

export const NAV_GROUPS: { key: NavGroup; labelKey: TranslationKey }[] = [
  { key: 'overview', labelKey: 'nav.overview' },
  { key: 'objects', labelKey: 'nav.objects' },
  { key: 'work', labelKey: 'nav.work' },
  { key: 'cleaning', labelKey: 'nav.cleaning' },
  { key: 'business', labelKey: 'nav.business' },
  { key: 'system', labelKey: 'nav.system' },
];

/** Vier Module in der Telefonnavigation; alles Weitere liegt unter «Mehr». */
export const MOBILE_NAV_KEYS: ModuleKey[] = ['dashboard', 'orders', 'damages', 'assets'];

export const moduleByKey = (key: ModuleKey): ModuleDefinition => {
  const found = MODULES.find((module) => module.key === key);
  if (!found) throw new Error(`Unbekanntes Modul: ${key}`);
  return found;
};

export const moduleByCollection = (collection: CollectionKey): ModuleDefinition =>
  moduleByKey(collection);
